#!/bin/bash

echo "EXEC ($(tty)): $*" | tee -a ex
cmd="srun --ntasks=1 --job-name=pycharm_helper"
for arg in "$@"; do
    if [[ "$arg" = $(pwd)/*.py ]]; then
        echo "  --> Starting SJOB with GPU" | tee -a ex
        if ! [[ $(tty) = "not a tty" ]]; then
            pty=' --pty'
        fi
        cmd="srun$pty --ntasks=1 --cpus-per-task=8 --mem=48G --gres=gpu:1 --job-name=AdaPoinTr"
    fi
done
$cmd /cluster/home/embe/mambaforge-pypy3/envs/PoinTr/bin/python "$@"
